### ISSUE TITLE
Support test.pypi.org

### ISSUE THREAD

**Issue by LucienShui** [Niraj-Kamdar/manylinux-wheel-builder#8]
Sometimes I need do some test under https://test.pypi.org, is there anyway to do that?

**Comment by Niraj-Kamdar** [comment]
Yes, you can do it by setting `TWINE_REPOSITORY` environment variable to `testpypi`. If not specified by default it will upload to main pypi repository. Here's the official documentation of twine for more information: https://twine.readthedocs.io/en/latest/

**Comment by LucienShui** [comment]
Okay, thanks a lot!
